# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: Build

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      configuration:
        required: true
        type: string
      enable_sanitizers:
        required: false
        type: boolean
      enable_coverage:
        required: false
        type: boolean
      publish_docker:
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{inputs.platform}}
    env:
      BUILD_TYPE: ${{inputs.configuration}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install prerequisites - Ubuntu-22.04
      if: inputs.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get install -y \
         gcc-multilib \
         libbpf-dev \
         lcov

    - name: Download daily nuget package and MSI
      env:
        GH_TOKEN: ${{ github.token }}
      if: inputs.platform == 'windows-2019' || inputs.platform == 'windows-2022'
      run: |
        mkdir ${{github.workspace}}/local_packages
        cd ${{github.workspace}}/local_packages
        $run = ((Invoke-WebRequest -Uri  "https://api.github.com/repos/microsoft/ebpf-for-windows/actions/runs?per_page=1&exclude_pull_requests=true&branch=main&status=completed&event=schedule").Content | ConvertFrom-Json)
        gh run download -R microsoft/ebpf-for-windows $run.workflow_runs.id -n "ebpf-for-windows - NuGet package (Build-x64_Release)"
        gh run download -R microsoft/ebpf-for-windows $run.workflow_runs.id -n "ebpf-for-windows - MSI installer (Build-x64_Release)"

    - name: Configure CMake
      if: inputs.platform == 'windows-2019' || inputs.platform == 'windows-2022'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBPF_PERF_LOCAL_NUGET_PATH=${{github.workspace}}/local_packages -DBPF_PERF_LOCAL_MSI_PATH=${{github.workspace}}/local_packages

    - name: Configure CMake
      if: inputs.platform == 'ubuntu-22.04'
      run: |
        if [ "${{inputs.enable_sanitizers}}" = "true" ]; then
          export SANITIZER_FLAGS="-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
        fi
        if [ "${{inputs.enable_coverage}}" = "true" ]; then
          export COVERAGE_FLAGS="-DCMAKE_CXX_FLAGS=\"--coverage\" -DCMAKE_C_FLAGS=\"--coverage\""
        fi
        cmake \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_CXX_FLAGS="${SANITIZER_FLAGS}" \
          -DCMAKE_C_FLAGS="${SANITIZER_FLAGS}" \
          ${COVERAGE_FLAGS}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{env.BUILD_TYPE}}-${{inputs.platform}}
        path: ${{github.workspace}}/build

    - name: Tests - Ubuntu-22.04
      if: inputs.platform == 'ubuntu-22.04'
      working-directory: ${{github.workspace}}/build/bin
      run: |
        sudo ./bpf_performance_runner tests.yml

    - name: Install prerequisites - Windows-2019 or Windows-2022
      if: inputs.platform == 'windows-2019' || inputs.platform == 'windows-2022'
      working-directory: ${{github.workspace}}/local_packages
      run: |
        Start-Process msiexec.exe -Wait -ArgumentList '/i ebpf-for-windows.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL'
        echo "C:\Program Files\ebpf-for-windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Tests - Windows 2019 or Windows 2022
      if: inputs.platform == 'windows-2019' || inputs.platform == 'windows-2022'
      working-directory: ${{github.workspace}}/build/bin
      shell: cmd
      run: |
        ${{env.BUILD_TYPE}}\bpf_performance_runner.exe tests_native.yml

    - name: Self-Tests
      if: inputs.platform == 'ubuntu-22.04'
      working-directory: ${{github.workspace}}/build/bin
      run: |
        cmake --build ${{github.workspace}}/build --target test --

    - name: Generate code coverage report
      if: inputs.enable_coverage == true
      run: |
        mkdir -p coverage
        lcov --capture --directory build --include '${{github.workspace}}/*' --output-file coverage/lcov.info --exclude '${{github.workspace}}/external/*' --exclude '${{github.workspace}}/build/*'

    - name: Coveralls Parallel
      if: inputs.enable_coverage == true
      uses: coverallsapp/github-action@v2.2.1
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{inputs.build_type}}-${{inputs.platform}}-${{inputs.arch}}
        parallel: true
