# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# Main YML file for the CICD pipeline

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Run on a daily schedule to perform the full set of tests.
  schedule:
    - cron: '00 21 * * *'

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  # Cancel any CI/CD workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: cicd-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        configuration: [ 'Release', 'Debug' ]
        platform: [ 'ubuntu-22.04', 'windows-2019', 'windows-2022' ]
        option: [ none, sanitizer, coverage ]
        exclude:
          - platform: [windows-2019, windows-2022]
            option: [ sanitizer, coverage ]

    uses: ./.github/workflows/Build.yml
    with:
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      option: ${{ matrix.option }}

  finish:
    needs:
      - build_and_test
    runs-on: ubuntu-22.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2.2.1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true


  # Note: This can't be in a workflow_call as the login action doesn't work.
  upload_results:
    needs:
      - build_and_test
    strategy:
      matrix:
        platforms: [ 'ubuntu-22.04', 'windows-2019', 'windows-2022' ]

    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: actions/checkout@v3

    - name: Download performance result artifacts
      uses: actions/download-artifact@v2
      with:
        name: results-Release-${{matrix.platform}}
        path: results

    - name: Post-process results
      run: |
        python3 scripts/process_results.py --csv-directory ${{github.workspace}}/results --sql-script-file ${{github.workspace}}/results/upload.sql --commit_id ${{github.sha}} --platform ${{matrix.platform}} --build_type ${{matrix.configuration}} --arch ${{matrix.arch}}

    - name: Upload performance data
      uses: azure/sql-action@v2.2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: ${{github.workspace}}/results/upload.sql

    - name: azure logout
      run: az logout